# DRAGON FORMUP left toolbar: (tool_id, title, tooltip description)
# tool_id is used by CanvasWidget / PhotoEditorWindow

LEFT_TOOLS: list[tuple[str, str, str]] = [
    ("move", "Move Tool", "Layer ya selection move karta hai."),
    ("artboard", "Artboard Tool", "Multiple artboards banata hai (stub)."),
    ("separator", "", ""),
    ("rectangular_marquee", "Rectangular Marquee", "Rectangle selection."),
    ("elliptical_marquee", "Elliptical Marquee", "Circle/ellipse selection."),
    ("single_row_marquee", "Single Row Marquee", "1-pixel high row selection."),
    ("single_column_marquee", "Single Column Marquee", "1-pixel wide column selection."),
    ("separator", "", ""),
    ("lasso", "Lasso Tool", "Freehand selection (polygon outline)."),
    ("polygonal_lasso", "Polygonal Lasso", "Click points for polygon (stub — use Lasso)."),
    ("magnetic_lasso", "Magnetic Lasso", "Edge-snapping lasso (stub)."),
    ("separator", "", ""),
    ("object_selection", "Object Selection", "Auto object bbox (approx)."),
    ("quick_selection", "Quick Selection", "Grow selection by edges (approx)."),
    ("magic_wand", "Magic Wand", "Same color connected area select."),
    ("separator", "", ""),
    ("crop", "Crop Tool", "Image crop — drag rectangle."),
    ("perspective_crop", "Perspective Crop", "Perspective crop (stub — use Crop)."),
    ("slice", "Slice Tool", "Web slices (stub)."),
    ("slice_select", "Slice Select", "Select slices (stub)."),
    ("separator", "", ""),
    ("frame", "Frame Tool", "Placeholder frame (stub)."),
    ("separator", "", ""),
    ("eyedropper", "Eyedropper", "Foreground color sample."),
    ("eyedropper_3d", "3D Material Eyedropper", "Not implemented."),
    ("color_sampler", "Color Sampler", "Multiple sample points (stub)."),
    ("ruler", "Ruler Tool", "Measure distance (stub)."),
    ("note", "Note Tool", "Notes (stub)."),
    ("count", "Count Tool", "Count objects (stub)."),
    ("separator", "", ""),
    ("spot_healing", "Spot Healing Brush", "Small blemish blur (approx)."),
    ("healing_brush", "Healing Brush", "Texture heal (approx blur)."),
    ("patch", "Patch Tool", "Replace region (stub)."),
    ("content_aware_move", "Content-Aware Move", "Use Edit > Content-Aware Fill."),
    ("red_eye", "Red Eye Tool", "Red tint reduction (approx)."),
    ("remove", "Remove Tool", "Inpaint remove (approx)."),
    ("separator", "", ""),
    ("brush", "Brush Tool", "Soft painting."),
    ("pencil", "Pencil Tool", "Hard edge painting."),
    ("color_replacement", "Color Replacement", "Replace hue along stroke (approx)."),
    ("mixer_brush", "Mixer Brush", "Smudge + paint mix (approx)."),
    ("separator", "", ""),
    ("clone_stamp", "Clone Stamp", "Alt+click source, then paint. Copy texture."),
    ("pattern_stamp", "Pattern Stamp", "Pattern along stroke (stub)."),
    ("separator", "", ""),
    ("history_brush", "History Brush", "Paint from snapshot (stub)."),
    ("art_history_brush", "Art History Brush", "Artistic (stub)."),
    ("separator", "", ""),
    ("eraser", "Eraser Tool", "Erase to transparent."),
    ("background_eraser", "Background Eraser", "Erase similar color (approx)."),
    ("magic_eraser", "Magic Eraser", "Delete connected color region."),
    ("separator", "", ""),
    ("gradient", "Gradient Tool", "Drag line: FG → BG gradient."),
    ("paint_bucket", "Paint Bucket", "Flood fill with foreground."),
    ("material_drop_3d", "3D Material Drop", "Not implemented."),
    ("separator", "", ""),
    ("blur_tool", "Blur Tool", "Local blur brush."),
    ("sharpen_tool", "Sharpen Tool", "Local sharpen brush."),
    ("smudge_tool", "Smudge Tool", "Smear pixels."),
    ("separator", "", ""),
    ("dodge", "Dodge Tool", "Lighten area."),
    ("burn", "Burn Tool", "Darken area."),
    ("sponge", "Sponge Tool", "Saturation up/down (Shift+drag)."),
    ("separator", "", ""),
    ("pen", "Pen Tool", "Vector path (stub)."),
    ("freeform_pen", "Freeform Pen", "Stub."),
    ("curvature_pen", "Curvature Pen", "Stub."),
    ("add_anchor", "Add Anchor Point", "Stub."),
    ("delete_anchor", "Delete Anchor Point", "Stub."),
    ("convert_point", "Convert Point Tool", "Stub."),
    ("separator", "", ""),
    ("type_horizontal", "Horizontal Type", "Type > Paste Lorem from menu."),
    ("type_vertical", "Vertical Type", "Stub."),
    ("type_mask_v", "Vertical Type Mask", "Stub."),
    ("type_mask_h", "Horizontal Type Mask", "Stub."),
    ("separator", "", ""),
    ("path_selection", "Path Selection", "Stub."),
    ("direct_selection", "Direct Selection", "Stub."),
    ("separator", "", ""),
    ("shape_rect", "Rectangle Tool", "Drag filled rectangle shape."),
    ("shape_ellipse", "Ellipse Tool", "Drag filled ellipse."),
    ("shape_triangle", "Triangle Tool", "Stub."),
    ("shape_polygon", "Polygon Tool", "Stub."),
    ("shape_line", "Line Tool", "Stub."),
    ("shape_custom", "Custom Shape Tool", "Stub."),
    ("separator", "", ""),
    ("hand", "Hand Tool", "Pan canvas (drag)."),
    ("rotate_view", "Rotate View Tool", "Canvas rotation (stub)."),
    ("zoom", "Zoom Tool", "Click zoom in; Alt+click zoom out."),
    ("separator", "", ""),
    ("quick_mask", "Quick Mask Mode", "Toggle quick mask."),
    ("screen_mode", "Screen Mode", "Toggle full screen window."),
    ("edit_toolbar", "Edit Toolbar", "Customize toolbar (stub)."),
]
